import { Inter } from 'next/font/google'
import './globals.css'
import NavBar from './Navegador/NavBar.js';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Appnotador',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <NavBar />
      <body className={inter.className}>{children}</body>
    </html>
  )
}
